---
- name: install base packages
  become: true
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - nano

- name: add a local splunk repository
  become: true
  yum_repository:
    reposdir: /etc/yum.repos.d
    name: splunk-repo
    description: Splunk
    file: splunk
    baseurl: "http://mgmt.{{ vars_location }}.splunk.lab/repo"
    gpgcheck: no
    enabled: yes
